name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Ou la branche où vous souhaitez que le pipeline soit déclenché (ex. : master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t yourusername/messaging-app:${{ github.sha }} .
        # `github.sha` permet de taguer l'image avec le commit hash, vous pouvez également utiliser une version ou autre tag

    - name: Push Docker image
      run: |
        docker push yourusername/messaging-app:${{ github.sha }}
        # Pousse l'image taguée vers Docker Hub
